from .SQLInjection import SQLInjection
from .CrossSiteScripting import CrossSiteScripting
from .CommandExecution import CommandExecution
from .FileInclusion import FileInclusion
from .InsecureEmail import InsecureEmail
from .XPATHInjection import XPATHInjection
from .LDAPInjection import LDAPInjection
from .HeaderInjection import HeaderInjection
from .OptionsUpdate import OptionsUpdate
